{
 "PRed": [
  {
   "PR": {
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python310"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 3,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "5.0.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 4,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy38"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 5,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1660433312.8647358,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "6.0.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 7,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1666895620.4396405,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "6.0.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 10,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "6.0.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 11,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python311"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [
     {
      "name": "bot-rerun"
     }
    ],
    "number": 12,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1684267136.823962,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "7.0.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "labels": [
     {
      "name": "bot-rerun"
     }
    ],
    "number": 13,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1696580006.7913356,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "8.0.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 15,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python312"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/1544921203.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "8.0.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/1608945907.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "9.0.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2023.11.19.09.00.44",
 "pre_pr_migrator_attempts": {
  "boost1780": 231,
  "boost_cpp_to_libboost": 101
 },
 "pre_pr_migrator_status": {
  "boost1780": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3339818468\">bot CI job</a>): main: ['linux_64_python3.10.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h99171d1_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_64_python3.8.____73_pypy: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h99171d1_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_64_python3.8.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h99171d1_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_64_python3.9.____73_pypy: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h99171d1_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_64_python3.9.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h99171d1_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_aarch64_python3.10.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h46bf9e6_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_aarch64_python3.8.____73_pypy: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h46bf9e6_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_aarch64_python3.8.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h46bf9e6_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_aarch64_python3.9.____73_pypy: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h46bf9e6_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_aarch64_python3.9.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h46bf9e6_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_python3.10.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h7c7db9d_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_python3.8.____73_pypy: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h7c7db9d_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_python3.8.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h7c7db9d_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_python3.9.____73_pypy: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h7c7db9d_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'linux_ppc64le_python3.9.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h7c7db9d_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'osx_64_python3.10.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h8ebb17e_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'osx_64_python3.8.____73_pypy: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h8ebb17e_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'osx_64_python3.8.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h8ebb17e_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'osx_64_python3.9.____73_pypy: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h8ebb17e_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'osx_64_python3.9.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-h8ebb17e_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'osx_arm64_python3.10.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-hf154d96_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'osx_arm64_python3.8.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-hf154d96_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n', 'osx_arm64_python3.9.____cpython: Encountered problems while solving:\\n  - package scine-utilsos-5.0.0-hf154d96_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed\\n']",
  "boost_cpp_to_libboost": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/7250243840'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nRuntimeError('Download error (28) Timeout was reached [https://conda.anaconda.org/msys2/noarch/repodata.json.zst]\\nOperation too slow. Less than 30 bytes/sec transferred the last 60 seconds')\n</pre>\n</div>\n</details>"
 },
 "smithy_version": "3.29.0"
}